[GateServer]
host = 127.0.0.1
port = 8080
[VarifyServer]
host = 127.0.0.1
port = 50051
[StatusServer]
host = 127.0.0.1
port = 50052
[Mysql]
host = 127.0.0.1
user = root
port = 33060
passwd = 123456
schema = chat_app_db
poolsize = 5
[Redis]
host = 127.0.0.1
port = 6379
passwd = 123456
[SelfChatServer]
name = ChatServer1
port = 8090
rpcport = 50055 ;聊天服务器之间使用rpc通信
[PeerServer] #配置其他聊天服务器
servers = ChatServer2,ChatServer3
[ChatServer2]
name = ChatServer2
host = 127.0.0.1
port = 8091
rpcport = 50056




;为什么要配置文件而不是去定义宏或者全局变量呢？对于大型项目，编译时间是很长的，如果每次修改配置都要重新编译，那会很麻烦，如果有配置文件，
;就可以在运行时动态修改配置，而不需要重新编译，这样就可以方便地修改配置，而不需要重新编译整个项目。